---
env:
  BEDROCK_CONFIG_PATH: '@dist_dir@/config'
  BEDROCK_SESSION_MANAGER: MemorySession

error_document:
  404: '@dist_dir@/htdocs/not-found.html'

overrides:
  BEDROCK_CONFIG_PATH: '@dist_dir@/config'
  BEDROCK_ERROR_LOCATION: '@dist_dir@/htdocs/error.roc'
  BEDROCK_IMAGE_DIR: '@dist_dir@/img'
  BEDROCK_INCLUDE_DIR: '@dist_dir@/include'
  BEDROCK_PEBBLE_DIR: '@dist_dir@/pebbles'
  LOG4PERL: '@dist_dir@/config/log4perl.conf'

session:
    enabled: yes
    binding: session
    session: yes
    module: BLM::Startup::MemorySession
    config:
      expiry_secs: 86400
      persistence_enabled: yes
      param: session
