---
# Bedrock's default miniserver configuration
parse_templates: true
log_level: info 
port: 80
error_document:
  404: '/@dist_dir@/htdocs/not-found.html'

services:
  /bedrock: Docs
  /bedrock-server-status: ServerStatus

# Add your document root here
#aliases:
#  /: html/

env:
  BEDROCK_CONFIG_PATH: '@dist_dir@/config'
  BEDROCK_SESSION_MANAGER: MemorySession
  BEDROCK_ERROR_LOCATION: '@dist_dir@/htdocs/fancy-error.roc'

overrides:
  LOG4PERL: '@dist_dir@/config/log4per.conf'

session:
  enabled: true
  binding: session
  session: yes
  module: BLM::Startup::MemorySession
  config:
    table_name: session
    expiry_secs: 900
    param: session
    log_level: info
    persistence_enable: no
