---
aliases:
  /bedrock/css: '@dist_dir@/css'
  /bedrock/img: '@dist_dir@/img'
  /bedrock/javascript: '@dist_dir@/javascript'
env:
  BEDROCK_CONFIG_PATH: '@dist_dir@/config'
  BEDROCK_SESSION_MANAGER: MemorySession
service_config:
  overrides:
    BEDROCK_CONFIG_PATH: '@dist_dir@/config'
    BEDROCK_ERROR_LOCATION: '@dist_dir@/htdocs/error.roc'
    BEDROCK_IMAGE_DIR: '@dist_dir@/img'
    BEDROCK_INCLUDE_DIR: '@dist_dir@/include'
    BEDROCK_PEBBLE_DIR: '@dist_dir@/pebbles'
    LOG4PERL: '@dist_dir@/config/log4perl.conf'
  default_session:
    enabled: yes
    binding: session
    session: yes
    module: BLM::Startup::MemorySession
    config:
      expiry_secs: 86400
      persistence_enabled: yes
      param: session
