---
aliases:
  /bedrock/css: '@dist_dir@/css'
  /bedrock/img: '@dist_dir@/img'
  /bedrock/javascript: '@dist_dir@/javascript'
env:
  BEDROCK_CONFIG_PATH: '@dist_dir@/config'
service_config:
  overrides:
    BEDROCK_CONFIG_PATH: '@dist_dir@/config'
    BEDROCK_ERROR_LOCATION: '@dist_dir@/htdocs/error.roc'
    BEDROCK_IMAGE_DIR: '@dist_dir@/img'
    BEDROCK_INCLUDE_DIR: '@dist_dir@/include'
    BEDROCK_PEBBLE_DIR: '@dist_dir@/pebbles'
    LOG4PERL: '@dist_dir@/config/log4perl.conf'
